//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanHotels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelPartner
    {
        public int PartnerID { get; set; }
        public int BranchId { get; set; }
        public string URL { get; set; }
        public string Details { get; set; }
        public string CouponCode { get; set; }
    
        public virtual HotelBranch HotelBranch { get; set; }
    }
}
