//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanHotels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomTypePrice
    {
        public int RoomTypePriceId { get; set; }
        public decimal Price { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int RoomTypeId { get; set; }
    
        public virtual RoomType RoomType { get; set; }
    }
}
