//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanHotels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomTypeAccessability
    {
        public RoomTypeAccessability()
        {
            this.RoomOccupancies = new HashSet<RoomOccupancy>();
            this.RoomTypeAvailabilities = new HashSet<RoomTypeAvailability>();
        }
    
        public int RoomTypeAccessabilityID { get; set; }
        public int RoomTypeID { get; set; }
        public int NoOfRooms { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
    
        public virtual ICollection<RoomOccupancy> RoomOccupancies { get; set; }
        public virtual ICollection<RoomTypeAvailability> RoomTypeAvailabilities { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
