//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationID { get; set; }
        public System.Guid ReservationNumber { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int CustomerId { get; set; }
        public int RoomTypeID { get; set; }
        public string PaymentMode { get; set; }
        public bool PaymentSuccess { get; set; }
        public bool CancellationStatus { get; set; }
        public Nullable<System.DateTime> CancelledAt { get; set; }
        public string CancellationRemarks { get; set; }
    }
}
